<a href="https://colab.research.google.com/github/francomanca93/analisis-de-datos/blob/comienzo/1-Comenzando-con-pandas/3_Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dataframes

Un DataFrame es una estructura de datos bidimensional, similar a una hoja de cálculo o una tabla SQL, que se utiliza en lenguajes como Python (con la librería Pandas) y R. Permite organizar datos en filas y columnas, donde cada columna puede contener datos de un tipo diferente (enteros, cadenas, booleanos, etc.)

In [1]:
# el paquete para usas dataframes
import pandas as pd
pd.__version__

'2.2.2'

Actualizando nuestra librería de pandas

In [6]:
# !pip install --upgrade pandas

In [10]:
# Crear un DataFrame desde un diccionario
import pandas as pd


datos = {
    'Nombre': ['Ana', 'Luis', 'Pedro'],
    'Edad': [23, 34, 29],
    'Ciudad': ['Bogotá', 'Medellín', 'Cali']
}

df = pd.DataFrame(datos)

In [11]:
df.describe()

            Edad
count   3.000000
mean   28.666667
std     5.507571
min    23.000000
25%    26.000000
50%    29.000000
75%    31.500000
max    34.000000

In [12]:
df.describe(include='all')

       Nombre       Edad  Ciudad
count       3   3.000000       3
unique      3        NaN       3
top       Ana        NaN  Bogotá
freq        1        NaN       1
mean      NaN  28.666667     NaN
std       NaN   5.507571     NaN
min       NaN  23.000000     NaN
25%       NaN  26.000000     NaN
50%       NaN  29.000000     NaN
75%       NaN  31.500000     NaN
max       NaN  34.000000     NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  3 non-null      object
 1   Edad    3 non-null      int64
 2   Ciudad  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [22]:
#   df.select_dtypes(include='object')
#   select_dtypes() es una función de pandas que te permite filtrar columnas por su tipo de dato.
#include='object' indica que se deben incluir solo las columnas de tipo "object", que normalmente son cadenas de texto (strings).

lista= df.select_dtypes(include='object')

lista2=lista.columns

In [24]:
# Veamos la descripcion de las variables

for col in lista2:
    print(f"Frecuencia de valores en '{col}':")
    print(df[col].value_counts())
    print()

Frecuencia de valores en 'Nombre':
Nombre
Ana      1
Luis     1
Pedro    1
Name: count, dtype: int64

Frecuencia de valores en 'Ciudad':
Ciudad
Bogotá      1
Medellín    1
Cali        1
Name: count, dtype: int64

In [29]:

# Existe una forma mas compacta

import pandas as pd

# Suponiendo que ya cargaste el DataFrame como df
resumen = []

for col in df.columns:
    tipo = df[col].dtype
    nulos = df[col].isnull().sum()  #
    unicos = df[col].nunique()

    if tipo == 'object' or df[col].dtype.name == 'category':
        ejemplos = df[col].value_counts().head(2).to_dict()
    else:
        ejemplos = None

    resumen.append({
        'Variable': col,
        'Tipo': tipo,
        'Nulos': nulos,
        'Valores únicos': unicos,
        'Ejemplos / Top categorías': ejemplos
    })

resumen_df = pd.DataFrame(resumen)
resumen_df.head(20)

  Variable    Tipo  Nulos  Valores únicos     Ejemplos / Top categorías
0   Nombre  object      0               3         {'Ana': 1, 'Luis': 1}
1     Edad   int64      0               3                          None
2   Ciudad  object      0               3  {'Bogotá': 1, 'Medellín': 1}

In [40]:
## Revisemos paso a paso
df['Nombre'].value_counts().head().to_dict()  # a Diccionario

{'Ana': 1, 'Luis': 1, 'Pedro': 1}

### Creando dataframe

In [43]:
dict_data = {'CO':100,'MX':200,'AR':300}
dict_data

{'CO': 100, 'MX': 200, 'AR': 300}

In [44]:
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

In [45]:
dict_data = {
    'CH': [100, 800, 200],
    'CO': [100, 200, 200],
    'AR': [300, 400, 400]
}

dict_data

{'CH': [100, 800, 200], 'CO': [100, 200, 200], 'AR': [300, 400, 400]}

In [46]:
df = pd.DataFrame(dict_data)

print(df)

    CH   CO   AR
0  100  100  300
1  800  200  400
2  200  200  400

Ahora creemos un dataframe un poco mas complejo y con mayor cantidad de datos tanto en columna como en filas.

In [47]:
import numpy as np

In [48]:
dict_data = {
    'edad': [10,9,13,14,12,11,12],
    'cm': [115,110,130,155,125,120,125],
    'pais':['co','mx','co','mx','mx','ch','ch'],
    'genero':['M','F','F','M','M','M','F'],
    'Q1':[5,10,8,np.nan,7,8,3],
    'Q2':[7,9,9,8,8,8,9]
}
dict_data

{'edad': [10, 9, 13, 14, 12, 11, 12],
 'cm': [115, 110, 130, 155, 125, 120, 125],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 9, 9, 8, 8, 8, 9]}

In [49]:
df = pd.DataFrame(dict_data)

print(df)

   edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  110   mx      F  10.0   9
2    13  130   co      F   8.0   9
3    14  155   mx      M   NaN   8
4    12  125   mx      M   7.0   8
5    11  120   ch      M   8.0   8
6    12  125   ch      F   3.0   9

In [52]:
#🧩 ¿Qué es index?
#  El argumento index= sirve para nombrar las filas. Por defecto, las filas están indexadas con números (0, 1, 2...),
# pero tú puedes poner etiquetas personalizadas como nombres o identificadores.


df = pd.DataFrame(dict_data, index = ['ana','benito','camilo','daniel','erika','fabian','gabriela'])

print(df)

          edad   cm pais genero    Q1  Q2
ana         10  115   co      M   5.0   7
benito       9  110   mx      F  10.0   9
camilo      13  130   co      F   8.0   9
daniel      14  155   mx      M   NaN   8
erika       12  125   mx      M   7.0   8
fabian      11  120   ch      M   8.0   8
gabriela    12  125   ch      F   3.0   9

## Conociendo a nuestro dataframe

Cuando se empiezar a analizar un set de datos luego de tenerlo como un dataframe(df) lo primero de debemos hacer es conocerlo, tanto como su estructura, tipos de datos, labels, etc.

df.info(): Te devuelve un resumen con la estructura de las variables y el tipo de datos que contienen.

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, ana to gabriela
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   edad    7 non-null      int64
 1   cm      7 non-null      int64
 2   pais    7 non-null      object
 3   genero  7 non-null      object
 4   Q1      6 non-null      float64
 5   Q2      7 non-null      int64
dtypes: float64(1), int64(3), object(2)
memory usage: 392.0+ bytes

df.describe(): Te devuelve un summary() de tu set de datos. Si tienes variables numericas te devolvera: minimo. maximo, media,std,…etc de las columnas numericas.

In [54]:
df.describe()

            edad          cm         Q1        Q2
count   7.000000    7.000000   6.000000  7.000000
mean   11.571429  125.714286   6.833333  8.285714
std     1.718249   14.556949   2.483277  0.755929
min     9.000000  110.000000   3.000000  7.000000
25%    10.500000  117.500000   5.500000  8.000000
50%    12.000000  125.000000   7.500000  8.000000
75%    12.500000  127.500000   8.000000  9.000000
max    14.000000  155.000000  10.000000  9.000000

Labels de filas y columnas

In [55]:
df.index

Index(['ana', 'benito', 'camilo', 'daniel', 'erika', 'fabian', 'gabriela'], dtype='object')

In [56]:
df.columns

Index(['edad', 'cm', 'pais', 'genero', 'Q1', 'Q2'], dtype='object')

Nos entrega una matriz con los datos del dataframe

In [57]:
df.values

array([[10, 115, 'co', 'M', 5.0, 7],
       [9, 110, 'mx', 'F', 10.0, 9],
       [13, 130, 'co', 'F', 8.0, 9],
       [14, 155, 'mx', 'M', nan, 8],
       [12, 125, 'mx', 'M', 7.0, 8],
       [11, 120, 'ch', 'M', 8.0, 8],
       [12, 125, 'ch', 'F', 3.0, 9]], dtype=object)

## Extracción de datos

In [58]:
df['edad']

ana         10
benito       9
camilo      13
daniel      14
erika       12
fabian      11
gabriela    12
Name: edad, dtype: int64

In [59]:
df[['edad', 'cm', 'Q1']]

          edad   cm    Q1
ana         10  115   5.0
benito       9  110  10.0
camilo      13  130   8.0
daniel      14  155   NaN
erika       12  125   7.0
fabian      11  120   8.0
gabriela    12  125   3.0

Con el metodo .loc podemos extraer datos utilizando los label tanto de las filas como de las columnas

In [61]:
df.loc['ana',['edad', 'cm', 'Q1']]

edad     10
cm      115
Q1      5.0
Name: ana, dtype: object

In [69]:
df.loc[['ana','erika'],['edad', 'cm', 'Q1']]

       edad   cm   Q1
ana      10  115  5.0
erika    12  125  7.0

In [70]:
print(df.loc['daniel','Q1'])

nan

In [71]:
threshold=df.loc['ana','Q1']
print(threshold)

5.0

In [91]:
# Cuando quieres todas las columnas excepto una
df_filtrado = df.loc[:, df.columns != 'Q2']
print(df_filtrado)

          edad   cm pais genero    Q1
ana         10  115   co      M   5.0
benito       9  110   mx      F  10.0
camilo      13  130   co      F   8.0
daniel      14  155   mx      M   NaN
erika       12  125   mx      M   7.0
fabian      11  120   ch      M   8.0
gabriela    12  125   ch      F   3.0

In [94]:
#Que pasa cuando quieres descartar dos columnas
df_filtrado = df.loc[:, ~df.columns.isin(['Q1', 'Q2'])]
print(df_filtrado)

          edad   cm pais genero
ana         10  115   co      M
benito       9  110   mx      F
camilo      13  130   co      F
daniel      14  155   mx      M
erika       12  125   mx      M
fabian      11  120   ch      M
gabriela    12  125   ch      F

In [109]:
#Claro, esa línea de código que estás usando es un ejemplo de una lista por comprensión
#comprehension), una característica muy poderosa y elegante de Python.
df_filtrado2 = df[[col for col in df.columns if col not  in ['Q1', 'Q2']]]
print(df_filtrado2)

          edad   cm pais genero
ana         10  115   co      M
benito       9  110   mx      F
camilo      13  130   co      F
daniel      14  155   mx      M
erika       12  125   mx      M
fabian      11  120   ch      M
gabriela    12  125   ch      F

Con el método .iloc puedo localizar elementos de mi dataframe a través de la posicion numerica de filas y columna.

In [98]:
print(df) # imprmimos nustro data frane

          edad   cm pais genero    Q1  Q2
ana         10  115   co      M   5.0   7
benito       9  110   mx      F  10.0   9
camilo      13  130   co      F   8.0   9
daniel      14  155   mx      M   NaN   8
erika       12  125   mx      M   7.0   8
fabian      11  120   ch      M   8.0   8
gabriela    12  125   ch      F   3.0   9

In [99]:
print(df.iloc[2,0])

13

In [100]:
print(df.iloc[[2, 4, 6],[1, 3]])  # Varias columnas

           cm genero
camilo    130      F
erika     125      M
gabriela  125      F

In [101]:
df.iloc[:,[1, 3]]

           cm genero
ana       115      M
benito    110      F
camilo    130      F
daniel    155      M
erika     125      M
fabian    120      M
gabriela  125      F

In [102]:
df.iloc[[0, 3],:]

        edad   cm pais genero   Q1  Q2
ana       10  115   co      M  5.0   7
daniel    14  155   mx      M  NaN   8

* df.loc: Para ubicar por el nombre de las columnas e indices
* df.iloc: Para ubicar por número de columna y fila

Utilizando .loc y .iloc podemos extraer subconjuntos de datos de un dataframe y poder extraer valor de los mismos.

## Filtrando datos

Gracias a los operadores relacionales puedo filtrar columnas o filas.

Ejemplo: Quiero de mi dataframe de la columna **edad** a todos los estudiantes mayores o iguales a 12

In [110]:
df['edad'] == 12

ana         False
benito      False
camilo      False
daniel      False
erika        True
fabian      False
gabriela     True
Name: edad, dtype: bool

El filtro anterior me da un columna con variables booleanas y lo puedo utilizar para formar un nuevo dataframe sin los valores False.

In [112]:
DF2=df[df['edad'] >= 12]
print(DF2)

          edad   cm pais genero   Q1  Q2
camilo      13  130   co      F  8.0   9
daniel      14  155   mx      M  NaN   8
erika       12  125   mx      M  7.0   8
gabriela    12  125   ch      F  3.0   9

Tambien puedo utilizar los operadores lógicos y concatenar mas de una consulta o filtro.

Ejemplo: Quiero a los mayores de 12 años y que sean de Mexico. A estos agregamelos en un nuevo dataframe.

In [113]:
data_ejemplo = df[(df['edad'] >= 12) & (df['pais'] == 'mx')]
print(data_ejemplo)

        edad   cm pais genero   Q1  Q2
daniel    14  155   mx      M  NaN   8
erika     12  125   mx      M  7.0   8

Tambien se puede utilizar la función query() de la siguiente manera.

In [117]:
print(df.query('edad > 12'))

        edad   cm pais genero   Q1  Q2
camilo    13  130   co      F  8.0   9
daniel    14  155   mx      M  NaN   8

In [122]:
##   Qué pasa cuando la logica es más compleja?
print(df.query("edad >= 12 and pais == 'mx'"))

        edad   cm pais genero   Q1  Q2
daniel    14  155   mx      M  NaN   8
erika     12  125   mx      M  7.0   8

La función query aumenta la legibilidad del código. Ejemplo:

In [124]:
##   Qué pasa cuando la logica es más compleja? Cuales son las diferencias

print(df.query( 'edad >= 12 and pais == "mx"'))

        edad   cm pais genero   Q1  Q2
daniel    14  155   mx      M  NaN   8
erika     12  125   mx      M  7.0   8

In [126]:
print( df[(df['edad'] >= 12) & (df['pais'] == 'mx')])

        edad   cm pais genero   Q1  Q2
daniel    14  155   mx      M  NaN   8
erika     12  125   mx      M  7.0   8

Muestran los mismos resultados pero el primero es mucho más legible que el segundo.

Tambien podemos comparar dos columnas que tengas los mismos tipos.

Ejemplo: Filtrame los que tengan en la columna de calificacion Q2 mayor o igual nota respecto a la columna Q1.

In [129]:
print(df['Q2'] >= df['Q1'])

ana          True
benito      False
camilo       True
daniel      False
erika        True
fabian       True
gabriela     True
dtype: bool

Formemos un nuevo dataframe con este filtro.

In [133]:
df['Logit'] = df['Q2'] >= df['Q1']
print(df)

          edad   cm pais genero    Q1  Q2  Logit
ana         10  115   co      M   5.0   7   True
benito       9  110   mx      F  10.0   9  False
camilo      13  130   co      F   8.0   9   True
daniel      14  155   mx      M   NaN   8  False
erika       12  125   mx      M   7.0   8   True
fabian      11  120   ch      M   8.0   8   True
gabriela    12  125   ch      F   3.0   9   True

In [137]:
# Obtener el número de filas y columnas
num_filas = len(df)
num_columnas = len(df.columns)

In [138]:
print('filas=' , num_filas, 'and Columnas=' ,num_columnas  )

filas= 7 and Columnas= 7

In [140]:
# Obtener la forma (shape) del DataFrame
forma = df.shape

print("Forma del DataFrame:", forma)
print("Número de filas:", forma[0])
print("Número de columnas:", forma[1])

Forma del DataFrame: (7, 7)
Número de filas: 7
Número de columnas: 7

In [141]:
#creacion de Variables

df['Rel_tall']= df['cm']+df['edad']**2

print(df)

          edad   cm pais genero    Q1  Q2  Logit  Rel_tall
ana         10  115   co      M   5.0   7   True       215
benito       9  110   mx      F  10.0   9  False       191
camilo      13  130   co      F   8.0   9   True       299
daniel      14  155   mx      M   NaN   8  False       351
erika       12  125   mx      M   7.0   8   True       269
fabian      11  120   ch      M   8.0   8   True       241
gabriela    12  125   ch      F   3.0   9   True       269

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, ana to gabriela
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   edad      7 non-null      int64
 1   cm        7 non-null      int64
 2   pais      7 non-null      object
 3   genero    7 non-null      object
 4   Q1        6 non-null      float64
 5   Q2        7 non-null      int64
 6   Logit     7 non-null      bool
 7   Rel_tall  7 non-null      int64
dtypes: bool(1), float64(1), int64(4), object(2)
memory usage: 755.0+ bytes

In [143]:
df['UPPERQ']= df['Q1']+df['Q2']

df

          edad   cm pais genero    Q1  Q2  Logit  Rel_tall  UPPERQ
ana         10  115   co      M   5.0   7   True       215    12.0
benito       9  110   mx      F  10.0   9  False       191    19.0
camilo      13  130   co      F   8.0   9   True       299    17.0
daniel      14  155   mx      M   NaN   8  False       351     NaN
erika       12  125   mx      M   7.0   8   True       269    15.0
fabian      11  120   ch      M   8.0   8   True       241    16.0
gabriela    12  125   ch      F   3.0   9   True       269    12.0

In [147]:
#funciones matematicas en df

import numpy as np

df['UPPERQ']= df['Q1']+np.log(df['Q2'])

df

          edad   cm pais genero    Q1  Q2  Logit  Rel_tall     UPPERQ
ana         10  115   co      M   5.0   7   True       215   6.945910
benito       9  110   mx      F  10.0   9  False       191  12.197225
camilo      13  130   co      F   8.0   9   True       299  10.197225
daniel      14  155   mx      M   NaN   8  False       351        NaN
erika       12  125   mx      M   7.0   8   True       269   9.079442
fabian      11  120   ch      M   8.0   8   True       241  10.079442
gabriela    12  125   ch      F   3.0   9   True       269   5.197225

In [148]:
df['Nueva_Variable'] = ''
#df.loc[(df['edad'] > 18) | (df['genero'] =='m'), 'Nueva_Variable'] = 'EXCLUIR'
#df.loc[(df['edad'] > 18) | (df['genero'] ='m'), 'Nueva_Variable'] = 'EXCLUIR'

In [ ]:
#ahora remplacemos q1 por nada
df.loc[(df['edad'] > 18) | (df['genero'] =='m'), 'Q1'] = 'NA'

In [150]:
df['UPPERQ']= df['Q1']+np.log(df['Q2'])

df['UPPERQ']

ana          6.945910
benito      12.197225
camilo      10.197225
daniel            NaN
erika        9.079442
fabian      10.079442
gabriela     5.197225
Name: UPPERQ, dtype: float64

 1. DataFrames para append() – Unión vertical (más filas)
 Ejemplo: estudiantes nuevos

In [152]:
import pandas as pd

# Primer grupo de estudiantes
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Nombre': ['Ana', 'Luis', 'Carlos'],
    'Ciudad': ['Bogotá', 'Cali', 'Medellín']
})

# Segundo grupo de estudiantes
df2 = pd.DataFrame({
    'ID': [4, 5],
    'Nombre': ['Diana', 'Pedro'],
    'Ciudad': ['Barranquilla', 'Bogotá']
})


df_append = pd.concat([df1, df2], ignore_index=True)

print("🔹 DataFrame combinado con append/concat:")
print(df_append)

🔹 DataFrame combinado con append/concat:
   ID  Nombre        Ciudad
0   1     Ana        Bogotá
1   2    Luis          Cali
2   3  Carlos      Medellín
3   4   Diana  Barranquilla
4   5   Pedro        Bogotá

 2. DataFrames para merge() – Unión horizontal (por columnas compartidas)
 Ejemplo: información de estudiantes + notas

In [155]:

# Notas de los estudiantes
df_notas = pd.DataFrame({
    'ID': [1, 2, 4, 5],
    'Nota': [4.5, 3.8, 4.2, 3.9]
})

# Unión horizontal por ID
df_merge = pd.merge(df1, df_notas, on='ID', how='left')

print("🔹 DataFrame combinado con merge:")
print(df_merge)

🔹 DataFrame combinado con merge:
   ID  Nombre    Ciudad  Nota
0   1     Ana    Bogotá   4.5
1   2    Luis      Cali   3.8
2   3  Carlos  Medellín   NaN

In [157]:
## tratamiento de datos ausentes
import pandas as pd
import numpy as np

# Creamos un DataFrame de ejemplo
df = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Diana', 'Pedro'],
    'Ciudad': ['Bogotá', 'Cali', np.nan, 'Barranquilla', 'Bogotá'],
    'Edad': [23, np.nan, 30, 22, 27],
    'Nota': [4.5, 3.8, np.nan, 4.2, 3.9]
})

print(" DataFrame original con datos nulos:")
print(df)

 DataFrame original con datos nulos:
   ID  Nombre        Ciudad  Edad  Nota
0   1     Ana        Bogotá  23.0   4.5
1   2    Luis          Cali   NaN   3.8
2   3  Carlos           NaN  30.0   NaN
3   4   Diana  Barranquilla  22.0   4.2
4   5   Pedro        Bogotá  27.0   3.9

In [159]:
df.isnull()

      ID  Nombre  Ciudad   Edad   Nota
0  False   False   False  False  False
1  False   False   False   True  False
2  False   False    True  False   True
3  False   False   False  False  False
4  False   False   False  False  False

In [160]:
df.isnull().sum()

ID        0
Nombre    0
Ciudad    1
Edad      1
Nota      1
dtype: int64

In [162]:
df_sin_nulos = df.dropna()

print(df_sin_nulos)

   ID Nombre        Ciudad  Edad  Nota
0   1    Ana        Bogotá  23.0   4.5
3   4  Diana  Barranquilla  22.0   4.2
4   5  Pedro        Bogotá  27.0   3.9

In [164]:
df_sin_columnas_nulas = df.dropna(axis=1)
print(df_sin_columnas_nulas)

   ID  Nombre
0   1     Ana
1   2    Luis
2   3  Carlos
3   4   Diana
4   5   Pedro

In [169]:
df_filled = df.fillna(0)
print(df_filled)

   ID  Nombre        Ciudad  Edad  Nota
0   1     Ana        Bogotá  23.0   4.5
1   2    Luis          Cali   0.0   3.8
2   3  Carlos             0  30.0   0.0
3   4   Diana  Barranquilla  22.0   4.2
4   5   Pedro        Bogotá  27.0   3.9

In [171]:
df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
print(df)

   ID  Nombre        Ciudad  Edad  Nota
0   1     Ana        Bogotá  23.0   4.5
1   2    Luis          Cali  25.5   3.8
2   3  Carlos           NaN  30.0   NaN
3   4   Diana  Barranquilla  22.0   4.2
4   5   Pedro        Bogotá  27.0   3.9

In [173]:
df.fillna(method='ffill', inplace=True)  # forward fill (rellena hacia abajo)
df.fillna(method='bfill', inplace=True)  # backward fill (hacia arriba)

/tmp/ipython-input-173-2574937119.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)  # forward fill (rellena hacia abajo)
/tmp/ipython-input-173-2574937119.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', inplace=True)  # backward fill (hacia arriba)

In [174]:
print(df)

   ID  Nombre        Ciudad  Edad  Nota
0   1     Ana        Bogotá  23.0   4.5
1   2    Luis          Cali  25.5   3.8
2   3  Carlos          Cali  30.0   3.8
3   4   Diana  Barranquilla  22.0   4.2
4   5   Pedro        Bogotá  27.0   3.9

In [175]:
df[df['Ciudad'].isnull()]

Empty DataFrame
Columns: [ID, Nombre, Ciudad, Edad, Nota]
Index: []

In [177]:
df['Ciudad'] = df['Ciudad'].fillna('Sin ciudad')